name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI PR Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v9.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: "gemini-2.5-flash" # 指定使用最新的輕量極速模型